# Generated by Django 4.1.4 on 2022-12-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_starting_date', models.DateField()),
                ('borrow_ending_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.borrower')),
            ],
        ),
    ]
