# Generated by Django 4.1.4 on 2022-12-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='edition_data',
            new_name='edition_date',
        ),
    ]
