# Generated by Django 4.1.4 on 2022-12-13 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='edition_data',
        ),
        migrations.AddField(
            model_name='book',
            name='edition_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=['%Y-%m-%d']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_ending_date',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_starting_date',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
    ]
